/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RepairsIndexRouteImport } from './routes/repairs.index'
import { Route as RepairsRepairIdRouteImport } from './routes/repairs.$repairId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairsIndexRoute = RepairsIndexRouteImport.update({
  id: '/repairs/',
  path: '/repairs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairsRepairIdRoute = RepairsRepairIdRouteImport.update({
  id: '/repairs/$repairId',
  path: '/repairs/$repairId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/repairs/$repairId': typeof RepairsRepairIdRoute
  '/repairs/': typeof RepairsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/repairs/$repairId': typeof RepairsRepairIdRoute
  '/repairs': typeof RepairsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/repairs/$repairId': typeof RepairsRepairIdRoute
  '/repairs/': typeof RepairsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/home'
    | '/login'
    | '/profile'
    | '/repairs/$repairId'
    | '/repairs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/home'
    | '/login'
    | '/profile'
    | '/repairs/$repairId'
    | '/repairs'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/home'
    | '/login'
    | '/profile'
    | '/repairs/$repairId'
    | '/repairs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RepairsRepairIdRoute: typeof RepairsRepairIdRoute
  RepairsIndexRoute: typeof RepairsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repairs/': {
      id: '/repairs/'
      path: '/repairs'
      fullPath: '/repairs/'
      preLoaderRoute: typeof RepairsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repairs/$repairId': {
      id: '/repairs/$repairId'
      path: '/repairs/$repairId'
      fullPath: '/repairs/$repairId'
      preLoaderRoute: typeof RepairsRepairIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RepairsRepairIdRoute: RepairsRepairIdRoute,
  RepairsIndexRoute: RepairsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
